### ISSUE TITLE
Haxelib

### ISSUE THREAD

**Issue by Masadow** [azrafe7/hxDelaunay#1]
This stuff is really cool

I would suggest you to make it available through haxelib. It would be very handy !

**Comment by Masadow** [comment]
(I received a mail about your reply but nothing show there ?)

**Comment by azrafe7** [comment]
Hi @Masadow, the reply wasn't from me, it was from @loudoweb (probably deleted his comment afterward).

By the way yes, putting this up on haxelib might be a good idea. I'm going to found out how to do that, thanks!

**Comment by Masadow** [comment]
If I have some spare time, I can do that for you this weekend with a pull
request, or at least, setup the repo :)

Jimmy Delas
Linkedin http://www.linkedin.com/profile/view?id=154981683
GitHub https://github.com/Masadow

On Thu, Apr 10, 2014 at 6:33 PM, Giuseppe Di Mauro <notifications@github.com

**Comment by azrafe7** [comment]
Hey I'd really appreciate a pull request! :thumbsup:

**Comment by azrafe7** [comment]
Not yet on haxelib, but take a look at @MatthijsKamstra effort here #2
